@baseURL = http://localhost:8080

### Criar Categoria

POST {{baseURL}}/categorias
Content-Type: ]application/json

{
    "nome": "informatica"

}

###Listar Categorias 


GET {{baseURL}}/categorias

###Criar Produtos vinculados a categoria

POST {{baseURL}}/produtos
Content-Type: application/json

{
    "nome": "Notebook",
    "descricao": "20gb de ram",
    "preco": 4000.00,
    "categoria": {"id": 1}
}

###buscar por faixa de preco

###buscar por categoria

GET {{baseURL}}/produtos/categoria/1

GET {{baseURL}}/produtos/faixa-preco?min=50&max=200